### ISSUE TITLE
zeek-script doesn't like `@` identifiers

### ISSUE THREAD

**Issue by rsmmr** [ckreibich/zeekscript#2]
When using [@DIR](https://docs.zeek.org/en/master/script-reference/directives.html#dir) in an expression, I get:

```
parsing error: cannot parse line 83, col 29: "@"
```

**Comment by ckreibich** [comment]
Good catch! `@FILENAME` also doesn't work. It's a tree-sitter grammar problem; I'll fix it over there. Its testsuite doesn't catch it because the Zeek scripts tree doesn't use these directives.
